version: '3'

services:
  backend:
    build: 
        context: ./Node-pokemon-back
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - frontend
    volumes:
      - ./Node-pokemon-back:/usr/src/app
      

  frontend:
    build:
      context: ./Next-pokemon-front      
    volumes:
      - ./Next-pokemon-front:/usr/src/app
    ports:
      - "3000:3000"
