version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./Next-pokemon-front      
    volumes:
      - .:/app
    ports:
      - "3000:3000"
